nohup: ignoring input
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /images/WhatsAppImage2025-07-26at12.30.16PM.jpeg HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /script.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /styles.css HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /videos/WhatsAppVideo2025-08-08at11.56.24PM.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /videos/WhatsAppVideo2025-09-01at9.37.15PM.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /videos/WhatsAppVideo2025-09-01at9.35.43PM.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57414)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/http/server.py", line 1296, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.11/http/server.py", line 657, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 431, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 419, in handle_one_request
    method()
  File "/usr/lib/python3.11/http/server.py", line 664, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.11/http/server.py", line 863, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /videos/WhatsAppVideo2025-08-08at11.56.24PM.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:18] "GET /videos/698e7b97d5411e33cc883a530f2b8697.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:19] "GET /videos/WhatsAppVideo2025-08-08at11.50.49PM.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57442)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/http/server.py", line 1296, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.11/http/server.py", line 657, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 431, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 419, in handle_one_request
    method()
  File "/usr/lib/python3.11/http/server.py", line 664, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.11/http/server.py", line 863, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
127.0.0.1 - - [03/Sep/2025 00:16:19] "GET /videos/WhatsAppVideo2025-09-01at9.37.15PM.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:19] "GET /videos/WhatsAppVideo2025-08-08at11.50.49PM(1).mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57430)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/http/server.py", line 1296, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.11/http/server.py", line 657, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 431, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 419, in handle_one_request
    method()
  File "/usr/lib/python3.11/http/server.py", line 664, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.11/http/server.py", line 863, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57472)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/http/server.py", line 1296, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.11/http/server.py", line 657, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 431, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 419, in handle_one_request
    method()
  File "/usr/lib/python3.11/http/server.py", line 664, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.11/http/server.py", line 863, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
127.0.0.1 - - [03/Sep/2025 00:16:19] "GET /videos/WhatsAppVideo2025-08-08at11.50.49PM.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [03/Sep/2025 00:16:19] "GET /videos/WhatsAppVideo2025-08-08at11.50.49PM(1).mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57502)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/http/server.py", line 1296, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.11/http/server.py", line 657, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 431, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 419, in handle_one_request
    method()
  File "/usr/lib/python3.11/http/server.py", line 664, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.11/http/server.py", line 863, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
127.0.0.1 - - [03/Sep/2025 00:16:19] code 404, message File not found
127.0.0.1 - - [03/Sep/2025 00:16:19] "GET /favicon.ico HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57508)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/http/server.py", line 1296, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.11/http/server.py", line 657, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 431, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 419, in handle_one_request
    method()
  File "/usr/lib/python3.11/http/server.py", line 664, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.11/http/server.py", line 863, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
